import streamlit as st
import time

# --- Page Config ---
st.set_page_config(page_title="Northstar Copilot Agent", page_icon="🤖", layout="wide")

# --- Mock Data (The "Backend") ---
# This makes the agent look intelligent without needing a real Salesforce connection
CRM_DATA = {
    "Acme Corp": {"deal_size": "$120,000", "contact": "Jane Doe", "stage": "Negotiation", "pain_points": ["Integration speed", "Security compliance"]},
    "Globex Inc": {"deal_size": "$45,000", "contact": "John Smith", "stage": "Discovery", "pain_points": ["Budget cuts"]}
}

EMAIL_CONTEXT = {
    "Acme Corp": "Subject: Re: Meeting. Jane mentioned they need the proposal by Friday. Focus on the 'Enterprise Security' module as that was their main concern in the Zoom call."
}

# --- Sidebar: User Context ---
with st.sidebar:
    st.header("Northstar Enterprise Hub")
    st.info("Log: User authenticated via Entra ID")
    st.write("**Connected Systems:**")
    st.success("✅ Dynamics 365 CRM")
    st.success("✅ SharePoint (Proposals)")
    st.success("✅ Outlook (Context)")
    
    st.divider()
    st.write("### 🛠️ Debug / Agent State")
    if "agent_status" not in st.session_state:
        st.session_state.agent_status = "Idle"
    st.code(f"Status: {st.session_state.agent_status}")

# --- Main UI ---
st.title("🤖 Sales Proposal Agent")
st.markdown("*Integrated into Microsoft 365 Copilot*")

st.chat_message("assistant").write("Hello! I'm your Sales Agent. I can draft proposals based on your CRM data and recent emails. Try asking: **'Draft a proposal for Acme Corp.'**")

# --- The Agent Logic ---
prompt = st.chat_input("What would you like to do?")

if prompt:
    st.chat_message("user").write(prompt)
    
    # 1. Intent Recognition
    if "proposal" in prompt.lower() and "acme" in prompt.lower():
        with st.status("Agent Reasoning...", expanded=True) as status:
            st.session_state.agent_status = "Gathering Context"
            
            # Step A: CRM Lookup
            st.write("🔍 **CRM Plugin:** Querying 'Acme Corp'...")
            time.sleep(1.5) # Fake latency to show "thinking"
            data = CRM_DATA["Acme Corp"]
            st.write(f"✅ **Found Opportunity:** Value {data['deal_size']} | Stage: {data['stage']}")
            
            # Step B: Email Analysis
            st.write("📧 **Outlook Connector:** Scanning recent threads...")
            time.sleep(1.5)
            st.write(f"💡 **Insight Detected:** Client emphasized '{data['pain_points'][1]}'. Adjusting proposal tone.")
            
            # Step C: Template Retrieval
            st.write("📂 **SharePoint Graph:** Retrieving 'Enterprise_SaaS_Template_v4.docx'...")
            time.sleep(1.0)
            
            status.update(label="Context Gathered! Drafting Document...", state="running")
            time.sleep(1.0)
            status.update(label="Complete", state="complete")
        
        # 2. Output Generation
        proposal_draft = f"""
        ### **Proposal for Acme Corp**
        **Prepared for:** {data['contact']}
        **Total Value:** {data['deal_size']}
        
        ---
        
        **Executive Summary**
        Thank you for the opportunity to partner with Acme Corp. Based on our discussion regarding **{data['pain_points'][0]}** and your strict requirements for **{data['pain_points'][1]}**, we have tailored this solution for you.
        
        **Proposed Solution**
        We will deploy the Northstar Enterprise Suite with the dedicated Security Module to ensure full compliance.
        
        * **Timeline:** 4 Weeks
        * **Investment:** {data['deal_size']} (Includes Q3 Discount)
        
        ---
        *Generated by Copilot. [Click to Edit in Word]*
        """
        
        st.chat_message("assistant").markdown(proposal_draft)
        st.button("✅ Approve & Send to Manager", type="primary")
        
    else:
        st.chat_message("assistant").write("I can currently only demonstrate the workflow for **Acme Corp**. Please try asking about that account!")